#Automatically generated by pip2arch on 2016-01-30

pkgname=python-css-html-prettify
pkgver=1.8.0
pkgrel=1
pkgdesc="StandAlone Async single-file cross-platform Unicode-ready Python3 Prettifier Beautifier for the Web."
url="https://github.com/juancarlospaco/css-html-prettify"
depends=('python' 'beautifulsoup4' 'pip')
makedepends=('python3' )
license=('CUSTOM')
arch=('any')
source=('https://pypi.python.org/packages/source/c/css-html-prettify/css-html-prettify-1.8.0.zip')
md5sums=('90cf0dee7b9b00602c46f5436ac185c4')

build() {
    cd $srcdir/css-html-prettify-1.8.0
    python setup.py build
}

package() {
    cd $srcdir/css-html-prettify-1.8.0
    python setup.py install --root="$pkgdir" --optimize=1 
}
