#Automatically generated by pip2arch on 2015-10-22

pkgname=python-css-html-prettify
pkgver=1.2.2
pkgrel=1
pkgdesc="StandAlone Async single-file cross-platform Unicode-ready Python3 Prettifier Beautifier for the Web."
url="https://github.com/juancarlospaco/css-html-prettify"
depends=('python' 'beautifulsoup4' 'pip')
makedepends=('python3' )
license=('CUSTOM')
arch=('any')
source=('https://pypi.python.org/packages/source/c/css-html-prettify/css-html-prettify-1.2.2.zip')
md5sums=('644b45def310602b0ec54938916c5593')

build() {
    cd $srcdir/css-html-prettify-1.2.2
    python setup.py build
}

package() {
    cd $srcdir/css-html-prettify-1.2.2
    python setup.py install --root="$pkgdir" --optimize=1 
}
